# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  agilemetricsserver:
    image: agilemetricsserver
    build:
      context: .
      dockerfile: AgileMetricsServer/Dockerfile
    ports:
      - 80:80
      - 443:443
